# Generated by Django 4.2.25 on 2025-11-10 18:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.group')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('stock_needed', models.JSONField()),
                ('max_produce', models.IntegerField(default=0)),
                ('original_max_produce', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=255)),
                ('production_cost_breakdown', models.JSONField(default=dict)),
                ('production_cost_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('wastage_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('wastage_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('inventory', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'production',
            },
        ),
        migrations.CreateModel(
            name='StockRemarks',
            fields=[
                ('stock', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('username', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'stock_remarks',
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('transaction_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=100)),
                ('details', models.JSONField()),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'stock_transactions',
            },
        ),
        migrations.CreateModel(
            name='UndoAction',
            fields=[
                ('undo_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=100)),
                ('undo_details', models.JSONField()),
                ('username', models.CharField(max_length=255)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'undo_actions',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('stock_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('defective', models.IntegerField(default=0)),
                ('total_quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('username', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.group')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='PushToProduction',
            fields=[
                ('push_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity_produced', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_deductions', models.JSONField()),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('username', models.CharField(max_length=255)),
                ('production_cost_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_production_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('timestamp', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
            options={
                'db_table': 'push_to_production',
            },
        ),
    ]
