# Generated by Django 5.2.8 on 2025-11-11 18:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CastingProduct',
            fields=[
                ('product_id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('stock_needed', models.JSONField(default=dict)),
                ('max_produce', models.IntegerField(default=0)),
                ('original_max_produce', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=255)),
                ('production_cost_breakdown', models.JSONField(default=dict)),
                ('production_cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('wastage_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('wastage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('inventory', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
